## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [1]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [37]:
# your code here
#model1 = nn.Sequential(OrderedDict([
#    ('hidden', nn.
#]))

model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 4)),
    ('tanh', nn.Tanh()),
    ('output', nn.Linear(4, 2)),
    ('sigmoid', nn.Sigmoid())
]))

  
model2 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 20)),
    ('sigmoid', nn.Sigmoid()),
    ('output', nn.Linear(20, 2)),
    ('sigmoid', nn.Sigmoid())
]))

model3 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 4)),
    ('leaky_relu', nn.LeakyReLU()),
    ('output', nn.Linear(4, 2)),
    ('tanh', nn.Tanh())
]))

In [38]:
print(model1)
print(model2)
print(model3)

Sequential(
  (hidden): Linear(in_features=2, out_features=4, bias=True)
  (tanh): Tanh()
  (output): Linear(in_features=4, out_features=2, bias=True)
  (sigmoid): Sigmoid()
)
Sequential(
  (hidden): Linear(in_features=2, out_features=20, bias=True)
  (sigmoid): Sigmoid()
  (output): Linear(in_features=20, out_features=2, bias=True)
)
Sequential(
  (hidden): Linear(in_features=2, out_features=4, bias=True)
  (leaky_relu): LeakyReLU(negative_slope=0.01)
  (output): Linear(in_features=4, out_features=2, bias=True)
  (tanh): Tanh()
)


In [39]:
# your code here
#data_in = torch.tensor( ...
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [40]:
# your code here
# data_target = torch.tensor( ...
data_target = torch.tensor([[0,0], [0,1], [0,1], [1,0]], dtype=torch.float)
print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [41]:
# your code here
# criterion = 
# optimizer = 

criterion = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1) # calculates gradients with learning rate 0.1
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.1)
optimizer3 = torch.optim.SGD(model3.parameters(), lr=0.1)

In [57]:
# your code here
# Train the model
first_epoch = 0
no_epochs = 1000

print('MODEL 1')
for epoch in range(no_epochs):
    # Forward pass
    output = model1(data_in)
    
    # Calculate the loss
    loss = criterion(output, data_target)
    
    # Backward pass and optimization
    optimizer1.zero_grad()
    loss.backward()
    optimizer1.step()

    # Print the loss every 100 epochs
    if (epoch+1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{no_epochs}] | Loss: {loss:.4f}")

    predicted_classes = (output.round() == data_target)
    accuracy = predicted_classes.sum().item() / len(data_target)
    if accuracy == 1 and first_epoch == 0:
        print(f"Model reached 100% accuracy at epoch {epoch+1}")
        first_epoch = 1


print('MODEL 2')
for epoch in range(no_epochs):
    # Forward pass
    output = model2(data_in)
    
    # Calculate the loss
    loss = criterion(output, data_target)
        
    # Backward pass and optimization
    optimizer2.zero_grad()
    loss.backward()
    optimizer2.step()
    
    # Print the loss every 100 epochs
    if (epoch+1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{no_epochs}] | Loss: {loss:.4f}")

    predicted_classes = (output.round() == data_target)
    accuracy = predicted_classes.sum().item() / len(data_target)
    if accuracy == 1 and first_epoch == 0:
        print(f"Model reached 100% accuracy at epoch {epoch+1}")
        first_epoch = 1

        
print('MODEL 3')
for epoch in range(no_epochs):
    # Forward pass
    output = model3(data_in)
    
    # Calculate the loss
    loss = criterion(output, data_target)
    
    # Backward pass and optimization
    optimizer3.zero_grad()
    loss.backward()
    optimizer3.step()
    
    # Print the loss every 100 epochs
    if (epoch+1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{no_epochs}] | Loss: {loss:.4f}")
        
        
    predicted_classes = (output.round() == data_target)
    accuracy = predicted_classes.sum().item() / len(data_target)
    if accuracy == 1 and first_epoch == 0:
        print(f"Model reached 100% accuracy at epoch {epoch+1}")
        first_epoch = 1
        

MODEL 1
Epoch [100/1000] | Loss: 0.0084
Epoch [200/1000] | Loss: 0.0079
Epoch [300/1000] | Loss: 0.0074
Epoch [400/1000] | Loss: 0.0070
Epoch [500/1000] | Loss: 0.0067
Epoch [600/1000] | Loss: 0.0064
Epoch [700/1000] | Loss: 0.0061
Epoch [800/1000] | Loss: 0.0058
Epoch [900/1000] | Loss: 0.0055
Epoch [1000/1000] | Loss: 0.0053
MODEL 2
Epoch [100/1000] | Loss: 0.0001
Epoch [200/1000] | Loss: 0.0000
Epoch [300/1000] | Loss: 0.0000
Epoch [400/1000] | Loss: 0.0000
Epoch [500/1000] | Loss: 0.0000
Epoch [600/1000] | Loss: 0.0000
Epoch [700/1000] | Loss: 0.0000
Epoch [800/1000] | Loss: 0.0000
Epoch [900/1000] | Loss: 0.0000
Epoch [1000/1000] | Loss: 0.0000
MODEL 3
Epoch [100/1000] | Loss: 0.0003
Epoch [200/1000] | Loss: 0.0003
Epoch [300/1000] | Loss: 0.0003
Epoch [400/1000] | Loss: 0.0003
Epoch [500/1000] | Loss: 0.0003
Epoch [600/1000] | Loss: 0.0003
Epoch [700/1000] | Loss: 0.0003
Epoch [800/1000] | Loss: 0.0003
Epoch [900/1000] | Loss: 0.0003
Epoch [1000/1000] | Loss: 0.0003


In [55]:
# your code here
# visualize the resuts

# for MODEL 1:

output = model1(data_in)

# Convert the output probabilities to binary predictions
predictions = (output >= 0.5).float()

# Print the model's predictions
print("Model 1's predictions:")
print(predictions)


# for MODEL 2:

output = model2(data_in)

# Convert the output probabilities to binary predictions
predictions = (output >= 0.5).float()

# Print the model's predictions
print("Model 2's predictions:")
print(predictions)


# for MODEL 3:

output = model3(data_in)

# Convert the output probabilities to binary predictions
predictions = (output >= 0.5).float()

# Print the model's predictions
print("Model 3's predictions:")
print(predictions)


Model 1's predictions:
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Model 2's predictions:
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Model 3's predictions:
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [50]:
# your code here
# print model wights


accuracies = []
models = [model1, model2, model3]
for model in models:
    model.eval()
    with torch.no_grad():
        outputs = model(data_in)
        predicted = (outputs >= 0.5).float()
        accuracy = (predicted == data_target).float().mean()
        accuracies.append(accuracy)

    print("Accuracy: {:.2f}%".format(accuracy.item() * 100))
    
# Select the best-performing model
best_model = models[accuracies.index(max(accuracies))]

print('Model ' + str(accuracies.index(max(accuracies)) + 1) + ' is the best!')

Accuracy: 75.00%
Accuracy: 87.50%
Accuracy: 100.00%
Model 3 is the best!
